### ISSUE TITLE
Animation Not Working

### ISSUE THREAD

**Issue by kael-moreno** [chengdazhi/DecentBanner#12]
I integrated your code through this:

> `DecentBanner bannerHeader = (DecentBanner) findViewById(R.id.viewPagerHeader);
>         List<View> sliderViews = new ArrayList<>();
>         ArrayList<String> titles = new ArrayList<>();
>             for (Slider slider: sliders) {
>             sliderViews.add(slider.getView(mContext));
>             titles.add("");
>         }

```
    bannerHeader.start(sliderViews, titles, 10, 5);
    bannerHeader.startAutoPlay();`
```

However, there's no animation. Am I missing something?

**Comment by chengdazhi** [comment]
@kaelitokael the fourth parameter is animation duration time in milliseconds, so if you want the animation to last for 5 seconds, you need to pass in 5000. If only half a second, then you need to pass in 500.

**Comment by kael-moreno** [comment]
@chengdazhi yes, I'm really sorry, my mistake. Will close this now.
