### ISSUE TITLE
Swipe from Right to left blank view until whole view slides in

### ISSUE THREAD

**Issue by eralpsahin** [chengdazhi/DecentBanner#18]
With two tabs, on auto play next tab slides correctly,  if I swipe manually, left to right swipe(previous tab) slides in correctly but right to left swipe(next tab) appears blank until the whole tab slides in. An Example screenshot added. This issue does not happen with three tabs(or probably with more than two tabs).
![screenshot_20170219-121311 1](https://cloud.githubusercontent.com/assets/10602289/23101500/ba088f60-f6a5-11e6-9635-f508fbf4673d.png)

**Comment by chengdazhi** [comment]
Hi, note that when you want to show less than 3 views, you need to extend the views to be no less than three items. When you want to display 2 views, your titles param should contain 2 items and your views param should contain 4 items as ABAB.

Please refer to the README document.
