### ISSUE TITLE
两个Tab的时候左滑有bug

### ISSUE THREAD

**Issue by kongnanlive** [chengdazhi/DecentBanner#7]
手动滑动的时候有白屏

**Comment by chengdazhi** [comment]
只有两个Tab的话需要在start方法中传入四个View，其中第一个和第三个是相同的，第二个和第四个相同。（其实我在README里写了，就是ABAB那段，可是我英语不好，没表达清楚。。）ViewPager会加载三个View，所以我采用了这种比较不专业的方案。。如果有其他解决方案请告诉我

**Comment by kongnanlive** [comment]
@chengdazhi 现在我也是这么干的。
还有，你可以封装下start方法中得views，这样就能很好的做一个广告轮播控件了。
目前这是我见过的最简洁的轮播控件了，谢谢你的贡献！

**Comment by hackware1993** [comment]
半个月就这么多star，想知道是如何推广的？

**Comment by chengdazhi** [comment]
@hackware1993 我在下面这篇文章的最后说到了推广，希望对你有所帮助。
[http://blog.chengdazhi.com/index.php/217](http://blog.chengdazhi.com/index.php/217)

**Comment by hackware1993** [comment]
@chengdazhi 嗯，我看看，谢啦
