### ISSUE TITLE
上传时报错

### ISSUE THREAD

**Issue by wei120698598** [chengdazhi/DecentBanner#9]
Error:FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':as_lib_CustomerView:bintrayUpload'.
> Could not create package 'xxxxx/maven/com.wei.view': HTTP/1.1 400 Bad Request [message:Package for path 'xxxxx/maven' was invalid. Package license is mandatory]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by chengdazhi** [comment]
抱歉我没能搞清你的问题，请问是哪个环节出了问题？你需要上传什么？

**Comment by wei120698598** [comment]
就是在执行过install后一切正常，在执行bintrayUpload时，报上面我给你发的错误，我查了查，没查到什么原因，我也检查了apikey，没有错误。你知道什么原因吗？谢谢。

**Comment by wei120698598** [comment]
也有可能是许可证的原因。有什么地方需要配置许可证吗？

**Comment by chengdazhi** [comment]
我在库module下的build.gradle中添加了几行代码，现在bintray代码块应该长这样
```
bintray {
    user = properties.getProperty("bintray.user")
    key = properties.getProperty("bintray.apikey")

    pkg {
        repo = 'maven'
        name = 'it.chengdazhi.decentbanner'

        version {
            name = '1.0.6-tuts'
            desc = "decent banner"
            released = new Date()
            vcsTag = '1.0.6'
        }

        licenses = ['Apache-2.0']
        vcsUrl = 'https://github.com/chengdazhi/DecentBanner.git'
        websiteUrl = 'https://github.com/chengdazhi/DecentBanner'
    }

    configurations = ['archives']
}
```
其中新添加的是pkg代码块内的最后三行，包含了licenses字段，你可以加上试试

**Comment by wei120698598** [comment]
我已经这样做的，上传成功了。多谢。
